name: Upload Python 3.9 tool cache
on: push
jobs:
  upload_tool_cache:
    runs-on: ubuntu-20.04
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Setup Terraform 1.4.6
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
      - name: Setup Terragrunt 0.46.3
        uses: eLco/setup-terragrunt@v1
        with:
          terragrunt_version: 0.46.3
      - name: Setup tflint 0.46.1
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.46.1
      - name: Setup tfsec 1.28.1
        uses: Flydiverny/setup-tfsec@v1
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
